services:

  postgres:
    image: docker.io/library/postgres:18
    container_name: postgres_skyjo
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./infra/postgres/init_sql/01_schema.sql:/docker-entrypoint-initdb.d/01_tables.sql
    networks:
      - NW_skyjo

  backend:
    build: ./backend/
    container_name: back_skyjo
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      JWT_SECRETKEY: ${JWT_SECRETKEY}
      API_KEY: ${API_KEY}
    networks:
        - NW_skyjo

  frontend:
    build: ./frontend/
    container_name: front_skyjo
    depends_on:
      - backend
    networks:
      - NW_skyjo

  nginx:
    build: ./infra/nginx/
    container_name: nginx_skyjo
    depends_on:
      - frontend
    ports:
      - "${APP_PORT}:443"
    networks:
      - NW_skyjo

  prometheus:
    container_name: prometheus_skyjo
    image: docker.io/prom/prometheus:v3.15.0-rc.0-distroless
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - NW_skyjo
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  NW_skyjo:
