

services:

  postgres:
    image: postgres:18
    container_name: postgres_skyjo
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - NW_skyjo

  backend:
    build: ./backend/
    container_name: back_skyjo
    ports: 
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    networks:
        - NW_skyjo

volumes:
  postgres_data:

networks:
  NW_skyjo:
